commit 396c1e990a0e513cf2e8510e9b6f82ab425c9e3a
Author: Dmitry Stogov <dmitry@zend.com>
Date:   Tue Nov 20 12:51:55 2012 +0400

    Fixed bug #63468 (wrong called method as callback with inheritance)

--- /dev/null
+++ php5/Zend/tests/bug63468.phpt
@@ -0,0 +1,30 @@
+--TEST--
+Bug #63468 (wrong called method as callback with inheritance)
+--FILE--
+<?php
+class Foo
+{
+	public function run()
+	{
+		return call_user_func(array('Bar', 'getValue'));
+	}
+
+	private static function getValue()
+	{
+		return 'Foo';
+	}
+}
+
+class Bar extends Foo
+{
+	public static function getValue()
+	{
+		return 'Bar';
+	}
+}
+
+$x = new Bar;
+var_dump($x->run());
+--EXPECT--
+string(3) "Bar"
+
--- php5.orig/Zend/zend_API.c
+++ php5/Zend/zend_API.c
@@ -2730,7 +2730,7 @@ static int zend_is_callable_check_func(i
 	} else if (zend_hash_find(ftable, lmname, mlen+1, (void**)&fcc->function_handler) == SUCCESS) {
 		retval = 1;
 		if ((fcc->function_handler->op_array.fn_flags & ZEND_ACC_CHANGED) &&
-		    EG(scope) &&
+		    !strict_class && EG(scope) &&
 		    instanceof_function(fcc->function_handler->common.scope, EG(scope) TSRMLS_CC)) {
 			zend_function *priv_fbc;
 
